package com.SS2HDemo.model;

// default package
// Generated 2017-9-19 21:41:00 by Hibernate Tools 5.2.5.Final

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String name;
	private String phone;

	public Customers() {
	}

	public Customers(String name, String phone) {
		this.name = name;
		this.phone = phone;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
